[tool.poetry]
name = "powershap"
version = "0.1.0"
description = "Feature selection using statistical significance of shap values"
authors = ["Jarne Verhaeghe"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.22.3"
pandas = "^1.4.1"
shap = "^0.40.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
